#!/bin/bash -e
# Example supervisor start/stop script.

# Assuming you placed a virtualenv here

SUPERVISORD=`which supervisord`
PIDFILE=$VIRTUAL_ENV/motor-blog/etc/supervisord.pid
OPTS="-c $VIRTUAL_ENV/motor-blog/etc/supervisord.conf"
. /lib/lsb/init-functions
export PATH="${PATH:+$PATH:}/usr/local/bin:/usr/sbin:/sbin"

case "$1" in
  start)
        log_begin_msg "Starting Supervisor daemon manager..."
        start-stop-daemon --start --quiet -p $PIDFILE -x $SUPERVISORD -- $OPTS || log_end_msg 1
        log_end_msg 0
        ;;
  stop)
        log_begin_msg "Stopping Supervisor daemon manager..."
        start-stop-daemon --stop --quiet --oknodo -p $PIDFILE || log_end_msg 1
        log_end_msg 0
        ;;

  restart|reload|force-reload)
        log_begin_msg "Restarting Supervisor daemon manager..."
        start-stop-daemon --stop --quiet --oknodo --retry 30 -p $PIDFILE
        start-stop-daemon --start --quiet -p $PIDFILE -x $SUPERVISORD -- $OPTS || log_end_msg 1
        log_end_msg 0
        ;;

  *)
        log_success_msg "Usage: supervisor
{start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
